# Generated by Django 6.0.2 on 2026-02-28 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="auto",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="core.auto"
            ),
        ),
    ]
