# Generated by Django 6.0.2 on 2026-02-28 23:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_venta_auto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="venta",
            old_name="precio_venta",
            new_name="total",
        ),
        migrations.RemoveField(
            model_name="venta",
            name="fecha_venta",
        ),
        migrations.AddField(
            model_name="auto",
            name="estado",
            field=models.CharField(
                choices=[
                    ("disponible", "Disponible"),
                    ("reservado", "Reservado"),
                    ("vendido", "Vendido"),
                ],
                default="disponible",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="fecha",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="auto",
            name="marca",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="auto",
            name="modelo",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="venta",
            name="auto",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="core.auto"
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="vendedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.vendedor"
            ),
        ),
    ]
