# Generated by Django 6.0.2 on 2026-03-01 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_precio_venta_venta_total_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comprador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                (
                    "dni_ruc",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="DNI / RUC"
                    ),
                ),
                ("telefono", models.CharField(max_length=20)),
                ("direccion", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Comprador",
                "verbose_name_plural": "Compradores",
            },
        ),
        migrations.AlterModelOptions(
            name="auto",
            options={"verbose_name": "Auto", "verbose_name_plural": "Autos"},
        ),
        migrations.AlterModelOptions(
            name="venta",
            options={"verbose_name": "Venta", "verbose_name_plural": "Ventas"},
        ),
        migrations.AddField(
            model_name="auto",
            name="color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="auto",
            name="combustible",
            field=models.CharField(
                choices=[
                    ("gasolina", "Gasolina"),
                    ("diesel", "Diésel"),
                    ("electrico", "Eléctrico"),
                    ("hibrido", "Híbrido"),
                    ("gas", "Gas"),
                ],
                default="gasolina",
                max_length=20,
                verbose_name="Tipo de combustible",
            ),
        ),
        migrations.AddField(
            model_name="auto",
            name="kilometraje",
            field=models.PositiveIntegerField(default=0, help_text="Kilometraje en km"),
        ),
        migrations.AddField(
            model_name="auto",
            name="vin",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Número VIN / Placa",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="comision_vendedor",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Comisión generada para el vendedor",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="descuento",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Descuento aplicado en soles",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="metodo_pago",
            field=models.CharField(
                choices=[
                    ("efectivo", "Efectivo"),
                    ("credito", "Crédito"),
                    ("transferencia", "Transferencia"),
                ],
                default="efectivo",
                max_length=20,
                verbose_name="Método de pago",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="numero_cuotas",
            field=models.PositiveIntegerField(
                default=1, help_text="1 = pago único, mayor a 1 = financiado"
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="comprador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.comprador",
            ),
        ),
    ]
