# Generated by Django 6.0.2 on 2026-03-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_comprador_alter_auto_options_alter_venta_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="anulada",
            field=models.BooleanField(default=False),
        ),
    ]
